Postfixvmail PFA-RC as web-apps

diff --git a/serfs/installrc b/serfs/installrc
--- a/serfs/installrc
+++ b/serfs/installrc
@@ -19,7 +19,6 @@
 
 CVAPPNAME=roundcube
 # Include the config files
-. /opt/verb/conf/servertype
 . /opt/verb/conf/sitenameip
 . /opt/verb/conf/siteurilist
 . /opt/verb/conf/sitemailpass
@@ -46,7 +45,7 @@ if [ ${SITEMAILSTATUS} = "EMAIL_NOT_INSTALLED" ]; then
 This is a backup email server and Roundcube is not allowed.
 "
 exit 8; fi
-if /bin/grep -Fq "Webmail Defaults" /opt/verb/conf/inkdns/inkzones/db.${emailTLDURI}; then
+if /bin/grep -Fq "Webmail Defaults" /opt/verb/conf/inkdns/zones/db.${emailTLDURI}; then
 /bin/echo "Proceeding..."; else
 /bin/echo "
 Webmail Defaults not declared in the DNS zone file. This won't work.
@@ -62,8 +61,20 @@ fi
 RCPASSGEN=$(/usr/bin/pwgen -s -1 5)
 DESSALTGEN=$(/usr/bin/pwgen -s -1 24)
 
-# Install package
-/usr/bin/pacman -S --noconfirm roundcubemail
+# Get inkVerb's latest and install
+cd /srv/www/email
+/opt/verb/serfs/inkget ${CVAPPNAME}; wait
+### Check
+/opt/verb/serfs/inkget ${CVAPPNAME} check
+if [ "$?" = 4 ]; then
+/bin/echo "Repo failed to retrieve the file."
+exit 4; fi
+if [ ! -f ${CVAPPNAME}.vtxz ]; then
+/bin/echo "Failed to retrieve from the repo."
+exit 4; fi
+
+/bin/rm -rf ${CVAPPNAME}
+/opt/verb/serfs/vtxzout ${CVAPPNAME}; wait
 
 # Directories
 ## Generate a symlink for the Verber
@@ -76,6 +87,50 @@ GRANT ALL PRIVILEGES ON rcmail.* TO 'rcmailusr'@'localhost' IDENTIFIED BY 'rcpas
 FLUSH PRIVILEGES;"
 ## Initialize the database before the installer page
 /usr/bin/mysql --defaults-extra-file=/opt/verb/conf/mysqlboss.cnf roundcube < /usr/share/webapps/roundcubemail/SQL/mysql.initial.sql
+
+# Webserver
+## Web directories
+/bin/cp -R /srv/www/html/0ne /srv/www/html/${SITEEMAILTLD}.rc
+/bin/ln -sfn /usr/share/webapps/roundcubemail /srv/www/html/${SITEEMAILTLD}.rc/${RCFOLDER}
+/bin/chown -R www:www /srv/www/html/${SITEEMAILTLD}.rc
+## DNS
+/bin/sed -i "s/; Webmail Defaults/; Webmail Defaults\nrc\.${emailTLDURI}\.\tIN  A\t\t${SITEIP}\nrc\.${emailTLDURI}\.\tIN  AAAA\t${SITEIPV6}/" /opt/verb/conf/inkdns/inkzones/db.${emailTLDURI}
+
+# Create the MySQL database and user
+/usr/bin/mysql --defaults-extra-file=/opt/verb/conf/mysqlboss.cnf -e "
+CREATE DATABASE rcmail DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
+GRANT ALL PRIVILEGES ON rcmail.* TO 'rcmailusr'@'localhost' IDENTIFIED BY 'rcpass${RCPASSGEN}';
+FLUSH PRIVILEGES;"
+
+# Set Apache
+/bin/cp -R /srv/www/html/0ne /srv/www/html/${SITEEMAILTLD}.rc
+/bin/ln -sfn /srv/www/email/roundcube /srv/www/html/${SITEEMAILTLD}.rc/${RCFOLDER}
+/bin/chown -R www-data:www-data /srv/www/html/${SITEEMAILTLD}.rc
+/bin/sed -i "s/; Webmail Defaults/; Webmail Defaults\nrc\.${emailTLDURI}\.\tIN  A\t\t${SITEIP}\nrc\.${emailTLDURI}\.\tIN  AAAA\t${SITEIPV6}/" /opt/verb/conf/inkdns/zones/db.${emailTLDURI}
+
+# inkCert
+## This adds the declared domain to the end of the "domains =" line
+/bin/sed -i "/^domains =/ s/$/, rc.${emailTLDURI}/" /opt/verb/conf/inkcert/cli-ini/cli.${emailTLDURI}.ini
+
+# Roundcube system apps
+/usr/bin/apt-get install -y \
+  php-mail \
+  php-mail-mimedecode \
+  php-mime-type \
+  php-mail-mime \
+  php-ldap \
+  libpspell-dev
+## The following dependencies often want to be installed after libpspell-dev, so do it differently
+wait
+/usr/bin/apt-get install -y \
+  php-pspell \
+  aspell-en  \
+## Install this silently so it doesn't get errors
+pear install -f Net_IDNA2-0.1.1
+## Should already be enabled, but enable just in case, Ex Ratione had some problems
+phpenmod intl zip
+/usr/sbin/apache2ctl graceful
+wait
 
 # Settings
 /bin/cp /opt/verb/conf/lab/vmail/roundcube/mime.types /srv/www/email/roundcube/
@@ -91,129 +146,69 @@ FLUSH PRIVILEGES;"
 /bin/sed -i "s/rcemailconfdeskeysalt286/${DESSALTGEN}/g" /srv/www/email/roundcube/config/config.inc.php
 # In the event that installpfa was run first
 if [ -e "/srv/www/email/postfixadmin/config.inc.php" ]; then
-/bin/sed  -i "s/rcfolder286/${RCFOLDER}/g" /srv/www/email/postfixadmin/config.inc.php
-fi
-
-# Webserver
-## Web directories
-/bin/cp -R /srv/www/html/0ne /srv/www/html/${SITEEMAILTLD}.rc
-/bin/ln -sfn /usr/share/webapps/roundcubemail /srv/www/html/${SITEEMAILTLD}.rc/${RCFOLDER}
-/bin/chown -R www:www /srv/www/html/${SITEEMAILTLD}.rc
-## DNS
-/bin/sed -i "s/; Webmail Defaults/; Webmail Defaults\nrc\.${emailTLDURI}\.\tIN  A\t\t${SITEIP}\nrc\.${emailTLDURI}\.\tIN  AAAA\t${SITEIPV6}/" /opt/verb/conf/inkdns/inkzones/db.${emailTLDURI}
-## Server type
-if [ ${SERVERTYPE} = "laemp" ] || [ ${SERVERTYPE} = "lamp" ]; then
-  /usr/bin/mv /opt/verb/conf/webserver/httpd/sites-available/pfa.${emailTLDURI}.conf /opt/verb/conf/webserver/httpd/sites-available/pfa.${emailTLDURI}.conf.old
-  /usr/bin/cp /opt/verb/conf/site-files/conf/rc.conf /opt/verb/conf/webserver/httpd/sites-available/rc.${emailTLDURI}.conf
-  /opt/verb/serfs/ensitenginx rc.${emailTLDURI}
-elif [ ${SERVERTYPE} = "lemp" ]; then
-  /usr/bin/mv /opt/verb/conf/webserver/nginx/sites-available/pfa.${emailTLDURI}.conf /opt/verb/conf/webserver/nginx/sites-available/pfa.${emailTLDURI}.conf.old
-  /usr/bin/cp /opt/verb/conf/site-files/conf/rc.conf /opt/verb/conf/webserver/nginx/sites-available/rc.${emailTLDURI}.conf
-  /opt/verb/serfs/ensiteapache rc.${emailTLDURI}
-fi
-
-# Write the config
-/bin/sed -i "s/SITEPFAPATH.*/SITEPFAPATH=\"${PFAFOLDER}\"/g" /opt/verb/conf/sitemailpath
-
-# Setup for inkCert
-. /opt/verb/conf/inkcert/cli-ini/siteinkcert.${emailTLDURI}
-case ${INKCERTED} in
-  DONE_SC)
-  /opt/verb/serfs/inkcertaddsc rc.${emailTLDURI} ${emailTLDURI}
-  ;;
-  DONE_IC)
-  /opt/verb/serfs/inkcertadd rc.${emailTLDURI} ${emailTLDURI}
-  ;;
-  DONE_LE)
-  /opt/verb/serfs/inkcertaddle rc.${emailTLDURI} ${emailTLDURI}
-  ;;
-  DONE_CB)
-  /opt/verb/serfs/inkcertaddcb rc.${emailTLDURI} ${emailTLDURI}
-  ;;
-  NO|NOT_YET)
-    /bin/echo "Nextcloud is currently using Snakeoil certs, ready for inkCert"
-  ;;
-  *)
-    if ! /bin/grep -q "INKCERTED=NO" /opt/verb/conf/inkcert/cli-ini/siteinkcert.${DOMAIN}; then
-      /bin/echo "Something's wrong with the inkCert siteinkcert configs! Aborting"
-      exit 6
-    else
-      /bin/echo "Nextcloud is currently using Snakeoil certs, ready for inkCert"
-    fi
-  ;;
-esac
-
-# Webserver restart
-if [ ${SERVERTYPE} = "laemp" ]; then
-  /usr/bin/systemctl restart nginx; wait
-  /usr/bin/systemctl restart httpd; wait
-elif [ ${SERVERTYPE} = "lemp" ]; then
-  /usr/bin/systemctl restart nginx; wait
-elif [ ${SERVERTYPE} = "lamp" ]; then
-  /usr/bin/systemctl restart httpd; wait
+/bin/sed -i "s/rcfolder286/${RCFOLDER}/g" /srv/www/email/postfixadmin/config.inc.php
 fi
 
 # Copy the branding files
-/bin/cp /opt/verb/conf/lab/vmail/roundcube/roundcubepics/verbink_logo.png /usr/share/webapps/roundcubemail/
-/bin/cp /opt/verb/conf/lab/vmail/roundcube/roundcubepics/skins/elastic/images/logo.svg /usr/share/webapps/roundcubemail/skins/elastic/images/
-/bin/cp /opt/verb/conf/lab/vmail/roundcube/roundcubepics/skins/elastic/images/favicon.ico /usr/share/webapps/roundcubemail/skins/elastic/images/
-/bin/cp /opt/verb/conf/lab/vmail/roundcube/roundcubepics/skins/larry/images/verbink_logo.png /usr/share/webapps/roundcubemail/skins/larry/images/
-/bin/cp /opt/verb/conf/lab/vmail/roundcube/roundcubepics/skins/larry/images/watermark.jpg /usr/share/webapps/roundcubemail/skins/larry/images/
-/bin/cp /opt/verb/conf/lab/vmail/roundcube/roundcubepics/skins/larry/images/favicon.ico /usr/share/webapps/roundcubemail/skins/larry/images/
+/bin/cp /opt/verb/conf/lab/vmail/roundcube/roundcubepics/verbink_logo.png /srv/www/email/roundcube/
+/bin/cp /opt/verb/conf/lab/vmail/roundcube/roundcubepics/skins/elastic/images/logo.svg /srv/www/email/roundcube/skins/elastic/images/
+/bin/cp /opt/verb/conf/lab/vmail/roundcube/roundcubepics/skins/elastic/images/favicon.ico /srv/www/email/roundcube/skins/elastic/images/
+/bin/cp /opt/verb/conf/lab/vmail/roundcube/roundcubepics/favicon.ico /srv/www/email/roundcube/
+/bin/cp /opt/verb/conf/lab/vmail/roundcube/roundcubepics/skins/larry/images/verbink_logo.png /srv/www/email/roundcube/skins/larry/images/
+/bin/cp /opt/verb/conf/lab/vmail/roundcube/roundcubepics/skins/larry/images/watermark.jpg /srv/www/email/roundcube/skins/larry/images/
+/bin/cp /opt/verb/conf/lab/vmail/roundcube/roundcubepics/skins/larry/images/favicon.ico /srv/www/email/roundcube/skins/larry/images/
 
-# Own again
-/bin/chown -R www:www /srv/www/html/${SITEEMAILTLD}.rc
+# Own
+/bin/chown -R www-data:www-data /srv/www/email/roundcube
 
 # Set the config for backup
 /bin/sed -i "s/SITERCPASSAPG.*/SITERCPASSAPG=\"${RCPASSGEN}\"/g" /opt/verb/conf/sitemailpass
 /bin/sed -i "s/SITERCPATH.*/SITERCPATH=\"${RCFOLDER}\"/g" /opt/verb/conf/sitemailpath
 
-#DEV This may not be necessary
 # Set up plugins that Composer broke
-#cd /srv/www/email/roundcube/plugins/
-#if [ ! -d "/srv/www/email/roundcube/plugins/authres_status" ]; then
-#/bin/cp /opt/verb/conf/lab/vmail/roundcube/authres_status.vtxz .
-#/opt/verb/serfs/vtxzout authres_status; wait; fi
-#if [ ! -d "/srv/www/email/roundcube/plugins/contextmenu" ]; then
-#/bin/cp /opt/verb/conf/lab/vmail/roundcube/contextmenu.vtxz .
-#/opt/verb/serfs/vtxzout contextmenu; wait; fi
+cd /srv/www/email/roundcube/plugins/
+if [ ! -d "/srv/www/email/roundcube/plugins/authres_status" ]; then
+/bin/cp /opt/verb/conf/lab/vmail/roundcube/authres_status.vtxz .
+/opt/verb/serfs/vtxzout authres_status; wait; fi
+if [ ! -d "/srv/www/email/roundcube/plugins/contextmenu" ]; then
+/bin/cp /opt/verb/conf/lab/vmail/roundcube/contextmenu.vtxz .
+/opt/verb/serfs/vtxzout contextmenu; wait; fi
 
-## Sledgehammertime (Composer Plugins)
-### This is excerpted from installrcinkplugins
-#cd /srv/www/email/roundcube
-#/usr/bin/curl -s https://getcomposer.org/installer | php
-#/bin/cp composer.json-dist composer.json
-### Plugins
-#### Unfortuntately, I only know how to sed this one line at a time.
-## Causing problems, reactivate when they decide on a minimum version number that doesn't exist in the future
-##sed -i '/\"require\": {/ a\
-##        \"johndoh\/contextmenu\": \"dev-master\",' composer.json
-#/bin/sed -i '/\"require\": {/ a\
-#        \"pear-pear.php.net\/net_ldap2\": \"dev-master\",' composer.json
-#/bin/sed -i '/\"require\": {/ a\
-#        \"kolab\/Net_LDAP3\": \"dev-master\",' composer.json
-#/bin/sed -i '/\"require\": {/ a\
-#        \"angrychimp\/php-dkim\": \"dev-master\",' composer.json
-#/bin/sed -i '/\"require\": {/ a\
-#        \"roundcube\/authres_status\": \"dev-master",' composer.json
-#/bin/sed -i '/\"require\": {/ a\
-#        \"cor\/keyboard_shortcuts\": \"dev-master\",' composer.json
-#/bin/sed -i '/\"require\": {/ a\
-#        \"johndoh\/markasjunk2\": \"dev-master\",' composer.json
-#/bin/sed -i '/\"require\": {/ a\
-#        \"kitist\/html5_notifier\": \"dev-master\",' composer.json
-#/bin/sed -i '/\"require\": {/ a\
-#        \"roundcube\/chbox\": \"dev-master\",' composer.json
-#/bin/sed -i '/\"require\": {/ a\
-#        \"roundcube\/custom-from\": \"dev-master\",' composer.json
-#/bin/sed -i '/\"require\": {/ a\
-#        \"elm\/identity_smtp\": \"dev-master\",' composer.json
+# Sledgehammertime (Composer Plugins)
+## This is excerpted from installrcinkplugins
+cd /srv/www/email/roundcube
+/usr/bin/curl -s https://getcomposer.org/installer | php
+/bin/cp composer.json-dist composer.json
+## Plugins
+### Unfortuntately, I only know how to sed this one line at a time.
+# Causing problems, reactivate when they decide on a minimum version number that doesn't exist in the future
+#sed -i '/\"require\": {/ a\
+#        \"johndoh\/contextmenu\": \"dev-master\",' composer.json
+/bin/sed -i '/\"require\": {/ a\
+        \"pear-pear.php.net\/net_ldap2\": \"dev-master\",' composer.json
+/bin/sed -i '/\"require\": {/ a\
+        \"kolab\/Net_LDAP3\": \"dev-master\",' composer.json
+/bin/sed -i '/\"require\": {/ a\
+        \"angrychimp\/php-dkim\": \"dev-master\",' composer.json
+/bin/sed -i '/\"require\": {/ a\
+        \"roundcube\/authres_status\": \"dev-master",' composer.json
+/bin/sed -i '/\"require\": {/ a\
+        \"cor\/keyboard_shortcuts\": \"dev-master\",' composer.json
+/bin/sed -i '/\"require\": {/ a\
+        \"johndoh\/markasjunk2\": \"dev-master\",' composer.json
+/bin/sed -i '/\"require\": {/ a\
+        \"kitist\/html5_notifier\": \"dev-master\",' composer.json
+/bin/sed -i '/\"require\": {/ a\
+        \"roundcube\/chbox\": \"dev-master\",' composer.json
+/bin/sed -i '/\"require\": {/ a\
+        \"roundcube\/custom-from\": \"dev-master\",' composer.json
+/bin/sed -i '/\"require\": {/ a\
+        \"elm\/identity_smtp\": \"dev-master\",' composer.json
 ## Now finish the composer installation
 ### First, update just in case, if you want
 #php composer.phar update -n
 ### Then, run install ( -n / --no-interaction = no interaction)
-#php composer.phar install -n # Composer doesn't like this run from root
-#/usr/bin/su slave -c 'php composer.phar install -n'
+/usr/bin/su slave -c 'php composer.phar install -n'
 
 # Finished
 /bin/echo "
