Postfixvmail beta
PFA & RC theoretically complete, untested

diff --git a/serfs/installrc b/serfs/installrc
--- a/serfs/installrc
+++ b/serfs/installrc
@@ -61,62 +61,24 @@ fi
 RCPASSGEN=$(/usr/bin/pwgen -s -1 5)
 DESSALTGEN=$(/usr/bin/pwgen -s -1 24)
 
-# Get inkVerb's latest and install
-cd /srv/www/email
-/opt/verb/serfs/inkget ${CVAPPNAME}; wait
-### Check
-/opt/verb/serfs/inkget ${CVAPPNAME} check
-if [ "$?" = 4 ]; then
-/bin/echo "Repo failed to retrieve the file."
-exit 4; fi
-if [ ! -f ${CVAPPNAME}.vtxz ]; then
-/bin/echo "Failed to retrieve from the repo."
-exit 4; fi
+# Install package
+/usr/bin/pacman -S --noconfirm roundcubemail
 
-/bin/rm -rf ${CVAPPNAME}
-/opt/verb/serfs/vtxzout ${CVAPPNAME}; wait
+# Directories
+## Generate a symlink for the Verber
+/usr/bin/ln -sfn /etc/webapps/roundcubemail /srv/www/email/roundcube
 
 # Create the MySQL database and user
 /usr/bin/mysql --defaults-extra-file=/opt/verb/conf/mysqlboss.cnf -e "
-CREATE DATABASE  rcmail;
+CREATE DATABASE `rcmail` DEFAULT CHARACTER SET `utf8` COLLATE `utf8_unicode_ci`;
 GRANT ALL PRIVILEGES ON rcmail.* TO 'rcmailusr'@'localhost' IDENTIFIED BY 'rcpass${RCPASSGEN}';
 FLUSH PRIVILEGES;"
-
-# Set Apache
-/bin/cp -R /srv/www/html/0ne /srv/www/html/${SITEEMAILTLD}.rc
-/bin/ln -sfn /srv/www/email/roundcube /srv/www/html/${SITEEMAILTLD}.rc/${RCFOLDER}
-/bin/chown -R www:www /srv/www/html/${SITEEMAILTLD}.rc
-/bin/sed -i "s/; Webmail Defaults/; Webmail Defaults\nrc\.${emailTLDURI}\.\tIN  A\t\t${SITEIP}\nrc\.${emailTLDURI}\.\tIN  AAAA\t${SITEIPV6}/" /opt/verb/conf/inkdns/zones/db.${emailTLDURI}
-/opt/verb/serfs/ensiteapache rc.${emailTLDURI}
-/usr/bin/apachectl graceful
-
-
-# inkCert
-## This adds the declared domain to the end of the "domains =" line
-/bin/sed -i "/^domains =/ s/$/, rc.${emailTLDURI}/" /opt/verb/conf/inkcert/cli-ini/cli.${emailTLDURI}.ini
-
-# Roundcube system apps
-/usr/bin/apt-get install -y \
-  php-mail \
-  php-mail-mimedecode \
-  php-mime-type \
-  php-mail-mime \
-  php-ldap \
-  libpspell-dev
-## The following dependencies often want to be installed after libpspell-dev, so do it differently
-wait
-/usr/bin/apt-get install -y \
-  php-pspell \
-  aspell-en  \
-## Install this silently so it doesn't get errors
-pear install -f Net_IDNA2-0.1.1
-## Should already be enabled, but enable just in case, Ex Ratione had some problems
-phpenmod intl zip
-/usr/bin/apachectl graceful
-wait
+## Initialize the database before the installer page
+/usr/bin/mysql --defaults-extra-file=/opt/verb/conf/mysqlboss.cnf roundcube < /usr/share/webapps/roundcubemail/SQL/mysql.initial.sql
 
 # Settings
 /bin/cp /opt/verb/conf/lab/vmail/roundcube/mime.types /srv/www/email/roundcube/
+#cp /etc/httpd/conf/mime.types /srv/www/email/roundcube/mime.types # If getting mime types from server
 /bin/cp /opt/verb/conf/lab/vmail/roundcube/config/roundcube286-config.inc.php /srv/www/email/roundcube/config/config.inc.php
 /bin/cp /opt/verb/conf/lab/vmail/roundcube/config/roundcube286-defaults.inc.php /srv/www/email/roundcube/config/defaults.inc.php
 /bin/sed -i "s/emailTLDURI286/${emailTLDURI}/g" /srv/www/email/roundcube/config/config.inc.php
@@ -131,6 +93,71 @@ if [ -e "/srv/www/email/postfixadmin/config.inc.php" ]; then
 /bin/sed  -i "s/rcfolder286/${RCFOLDER}/g" /srv/www/email/postfixadmin/config.inc.php
 fi
 
+# Webserver
+## Web directories
+/bin/cp -R /srv/www/html/0ne /srv/www/html/${SITEEMAILTLD}.rc
+/bin/ln -sfn /usr/share/webapps/roundcubemail /srv/www/html/${SITEEMAILTLD}.rc/${RCFOLDER}
+/bin/chown -R www:www /srv/www/html/${SITEEMAILTLD}.rc
+## DNS
+/bin/sed -i "s/; Webmail Defaults/; Webmail Defaults\nrc\.${emailTLDURI}\.\tIN  A\t\t${SITEIP}\nrc\.${emailTLDURI}\.\tIN  AAAA\t${SITEIPV6}/" /opt/verb/conf/inkdns/zones/db.${emailTLDURI}
+## Server type
+if [ ${SERVERTYPE} = "laemp" ]; then
+  /usr/bin/mv /opt/verb/conf/webserver/nginx/sites-available/rc.${emailTLDURI}.conf /opt/verb/conf/webserver/nginx/sites-available/rc.${emailTLDURI}.conf.old
+  /usr/bin/cp /opt/verb/conf/site-files/conf/nextcloud.conf /opt/verb/conf/webserver/nginx/sites-available/rc.${emailTLDURI}.conf
+  /usr/bin/mv /opt/verb/conf/webserver/httpd/sites-available/rc.${emailTLDURI}.conf /opt/verb/conf/webserver/httpd/sites-available/rc.${emailTLDURI}.conf.old
+  /usr/bin/rm /opt/verb/conf/webserver/httpd/sites-enabled/${emailTLDURI}.conf
+  /opt/verb/serfs/ensitenginx rc.${emailTLDURI}
+elif [ ${SERVERTYPE} = "lemp" ]; then
+  /usr/bin/mv /opt/verb/conf/webserver/nginx/sites-available/rc.${emailTLDURI}.conf /opt/verb/conf/webserver/nginx/sites-available/rc.${emailTLDURI}.conf.old
+  /usr/bin/cp /opt/verb/conf/site-files/conf/nextcloud.conf /opt/verb/conf/webserver/nginx/sites-available/rc.${emailTLDURI}.conf
+  /opt/verb/serfs/ensitenginx rc.${emailTLDURI}
+elif [ ${SERVERTYPE} = "lamp" ]; then
+  /usr/bin/mv /opt/verb/conf/webserver/httpd/sites-available/rc.${emailTLDURI}.conf /opt/verb/conf/webserver/httpd/sites-available/rc.${emailTLDURI}.conf.old
+  /usr/bin/cp /opt/verb/conf/site-files/conf/nextcloud.conf /opt/verb/conf/webserver/httpd/sites-available/rc.${emailTLDURI}.conf
+  /opt/verb/serfs/ensiteapache rc.${emailTLDURI}
+fi
+
+# Write the config
+/bin/sed -i "s/SITEPFAPATH.*/SITEPFAPATH=\"${PFAFOLDER}\"/g" /opt/verb/conf/sitemailpath
+
+# Setup for inkCert
+. /opt/verb/conf/inkcert/cli-ini/siteinkcert.${emailTLDURI}
+case ${INKCERTED} in
+  DONE_SC)
+  /opt/verb/serfs/inkcertaddsc rc.${emailTLDURI}
+  ;;
+  DONE_IC)
+  /opt/verb/serfs/inkcertadd rc.${emailTLDURI}
+  ;;
+  DONE_LE)
+  /opt/verb/serfs/inkcertaddle rc.${emailTLDURI}
+  ;;
+  DONE_CB)
+  /opt/verb/serfs/inkcertaddcb rc.${emailTLDURI}
+  ;;
+  NO|NOT_YET)
+    /bin/echo "Nextcloud is currently using Snakeoil certs, ready for inkCert"
+  ;;
+  *)
+    if ! /bin/grep -q "INKCERTED=NO" /opt/verb/conf/inkcert/cli-ini/siteinkcert.${DOMAIN}; then
+      /bin/echo "Something's wrong with the inkCert siteinkcert configs! Aborting."
+      exit 6
+    else
+      /bin/echo "Nextcloud is currently using Snakeoil certs, ready for inkCert"
+    fi
+  ;;
+esac
+
+# Webserver restart
+if [ ${SERVERTYPE} = "laemp" ]; then
+  /usr/bin/systemctl restart nginx; wait
+  /usr/bin/systemctl restart httpd; wait
+elif [ ${SERVERTYPE} = "lemp" ]; then
+  /usr/bin/systemctl restart nginx; wait
+elif [ ${SERVERTYPE} = "lamp" ]; then
+  /usr/bin/systemctl restart httpd; wait
+fi
+
 # Copy the branding files
 /bin/cp /opt/verb/conf/lab/vmail/roundcube/roundcubepics/verbink_logo.png /srv/www/email/roundcube/
 /bin/cp /opt/verb/conf/lab/vmail/roundcube/roundcubepics/skins/elastic/images/logo.svg /srv/www/email/roundcube/skins/elastic/images/
@@ -140,21 +167,22 @@ fi
 /bin/cp /opt/verb/conf/lab/vmail/roundcube/roundcubepics/skins/larry/images/watermark.jpg /srv/www/email/roundcube/skins/larry/images/
 /bin/cp /opt/verb/conf/lab/vmail/roundcube/roundcubepics/skins/larry/images/favicon.ico /srv/www/email/roundcube/skins/larry/images/
 
-# Own
-/bin/chown -R www:www /srv/www/email/roundcube
+# Own again
+/bin/chown -R www:www /srv/www/html/${SITEEMAILTLD}.rc
 
 # Set the config for backup
 /bin/sed -i "s/SITERCPASSAPG.*/SITERCPASSAPG=\"${RCPASSGEN}\"/g" /opt/verb/conf/sitemailpass
 /bin/sed -i "s/SITERCPATH.*/SITERCPATH=\"${RCFOLDER}\"/g" /opt/verb/conf/sitemailpath
 
+#DEV This may not be necessary
 # Set up plugins that Composer broke
-cd /srv/www/email/roundcube/plugins/
-if [ ! -d "/srv/www/email/roundcube/plugins/authres_status" ]; then
-/bin/cp /opt/verb/conf/lab/vmail/roundcube/authres_status.vtxz .
-/opt/verb/serfs/vtxzout authres_status; wait; fi
-if [ ! -d "/srv/www/email/roundcube/plugins/contextmenu" ]; then
-/bin/cp /opt/verb/conf/lab/vmail/roundcube/contextmenu.vtxz .
-/opt/verb/serfs/vtxzout contextmenu; wait; fi
+#cd /srv/www/email/roundcube/plugins/
+#if [ ! -d "/srv/www/email/roundcube/plugins/authres_status" ]; then
+#/bin/cp /opt/verb/conf/lab/vmail/roundcube/authres_status.vtxz .
+#/opt/verb/serfs/vtxzout authres_status; wait; fi
+#if [ ! -d "/srv/www/email/roundcube/plugins/contextmenu" ]; then
+#/bin/cp /opt/verb/conf/lab/vmail/roundcube/contextmenu.vtxz .
+#/opt/verb/serfs/vtxzout contextmenu; wait; fi
 
 # Sledgehammertime (Composer Plugins)
 ## This is excerpted from installrcinkplugins
